# Generated by Django 3.1.7 on 2021-05-22 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktools', '0002_worktool_has_been_in_mainteance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worktool',
            old_name='speacifications',
            new_name='specifications',
        ),
    ]
